//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public System.DateTime Date_Exam { get; set; }
        public Nullable<int> Id_Subject { get; set; }
        public int Id_Student { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public string Auditory { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Id_Exam { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
